name: testing

services:
  redisai:
    image: redis:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  memcached:
    image: memcached:1
    command: -I 32m
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - node.name=os01
      - discovery.seed_hosts=os01
      - cluster.initial_master_nodes=os01
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
    volumes:
      - ./search/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.testing_db.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  search:
    image: arthistlmu/artigo_search:master
    volumes:
      - type: bind
        source: ./dump_testing/
        target: /dump
    working_dir: /search/src/artigo_search
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/search/src/
    depends_on:
      - api
      - redisai
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  api:
    image: arthistlmu/artigo_api:master
    volumes:
      - type: bind
        source: ./media/
        target: /media
      - type: bind
        source: ./dump_testing/
        target: /dump
    working_dir: /api/src/artigo_api
    depends_on:
      - db
      - redisai
      - memcached
    env_file:
      - ./.testing_api.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  
  api-proxy:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./api-proxy/api-proxy-nginx.conf
        target: /etc/nginx/conf.d/api-proxy-nginx.conf
        read_only: true
      - type: bind
        source: ./api-proxy/uwsgi_params
        target: /uwsgi_params
        read_only: true
      - type: bind
        source: ./media
        target: /media
      - type: bind
        source: ./api/src/artigo_api/static
        target: /static
        read_only: true
    depends_on:
      - api
    ports:
      - "8001:8000"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  web:
    image: arthistlmu/artigo:master
    depends_on:
      - api
    ports:
      - "8081:80"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  db_data:
