name: production

services:
  redisai:
    image: redis:latest
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  memcached:
    image: memcached:1
    restart: always
    command: -I 32m
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  opensearch:
    build:
      context: .
      dockerfile: ./search/config/Dockerfile
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    volumes:
      - ./search/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.production_db.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  search:
    image: arthistlmu/artigo_search:latest
    restart: always
    volumes:
      - ./dump_production/:/dump
    working_dir: /search/src/artigo_search
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/search/src/
    depends_on:
      - api
      - redisai
    env_file:
      - ./.production_api.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  api:
    image: arthistlmu/artigo_api:latest
    restart: always
    volumes:
      - ./media/:/media
      - ./dump_production/:/dump
    working_dir: /api/src/artigo_api
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
    depends_on:
      - db
      - redisai
      - memcached
    env_file:
      - ./.production_api.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  api-proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./media/:/media
      - type: bind
        source: ./api-proxy/api-proxy-nginx.conf
        target: /etc/nginx/conf.d/api-proxy-nginx.conf
        read_only: true
      - type: bind
        source: ./api-proxy/uwsgi_params
        target: /uwsgi_params
        read_only: true
      - type: bind
        source: ./api/src/artigo_api/static
        target: /static
        read_only: true
    depends_on:
      - api
    ports:
      - "8000:8000"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  web:
    image: arthistlmu/artigo:latest
    restart: always
    depends_on:
      - api
    ports:
      - "8080:80"
    env_file:
      - ./.production_api.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  db_data:
