version: "3.2"
services:
  redisai:
    image: redislabs/redisai:edge-cpu-bionic

  db:
    image: postgres:13
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artigo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    image: artigo/api
    build:
      context: ./api
    volumes:
      - type: bind
        # TODO: change path
        source: ./media/
        target: /media
      - type: bind
        # TODO: change path
        source: ./dump/
        target: /dump
      - type: bind
        source: ./api/
        target: /api
    working_dir: /api/src
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redisai
    ports:
      - "127.0.0.1:8000:8000"
    
  celery:
    image: artigo/api
    build:
      context: ./api
    volumes:
      - type: bind
        # TODO: change path
        source: ./media/
        target: /media
      - type: bind
        # TODO: change path
        source: ./dump/
        target: /dump
      - type: bind
        source: ./api/
        target: /api
    working_dir: /api/src
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
    command: celery -A core worker -l INFO
    depends_on:
      - db
      - redisai
    
  web:
    image: artigo/web
    build:
      context: ./web
    volumes:
      - type: bind
        source: ./web/
        target: /web
    working_dir: /web
    depends_on:
      - api
    ports:
      - "127.0.0.1:80:80"
