version: "3"
name: production

services:
  redisai:
    image: redis:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  memcached:
    image: memcached:1
    command: -I 32m
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - node.name=os01
      - discovery.seed_hosts=os01
      - cluster.initial_master_nodes=os01
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
    volumes:
      - ./search/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.production_db.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  search:
    image: arthistlmu/artigo_search:latest
    volumes:
      - type: bind
        source: ./dump/
        target: /dump
    working_dir: /search/src/artigo_search
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/search/src/
    depends_on:
      - api
      - redisai
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  api:
    image: arthistlmu/artigo_api:latest
    volumes:
      - type: bind
        source: ./media/
        target: /media
      - type: bind
        source: ./dump/
        target: /dump
    working_dir: /api/src/artigo_api
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
    depends_on:
      - db
      - redisai
      - memcached
    env_file:
      - ./.production_api.env
    ports:
      - "8000:8000"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  web:
    image: arthistlmu/artigo:latest
    depends_on:
      - api
    ports:
      - "8080:80"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  db_data:
