version: "3.2"

services:
  redisai:
    image: redislabs/redisai:edge-cpu-bionic

  memcached:
    image: memcached:1
    command: -I 32m

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - node.name=os01
      - discovery.seed_hosts=os01
      - cluster.initial_master_nodes=os01
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
    volumes:
      # - ./search/config/perf/:/usr/share/opensearch/data/
      - ./search/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  db:
    image: postgres:14
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artigo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  search:
    image: artigo/search
    build:
      context: ./search
    volumes:
      - type: bind
        source: ./dump/
        target: /dump
      - type: bind
        source: ./search/
        target: /search
      - type: bind
        source: ./search/config.json
        target: /config.json
    working_dir: /search/src/artigo_search
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/search/src/
      # - GRPC_VERBOSITY=debug
    depends_on:
      - api
      - redisai

  api:
    image: artigo/api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - type: bind
        source: ./media/
        target: /media
      - type: bind
        source: ./dump/
        target: /dump
      - type: bind
        source: ./api/
        target: /api
      - type: bind
        source: ./api/config.json
        target: /config.json
    working_dir: /api/src/artigo_api
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
    depends_on:
      - db
      - redisai
      - memcached
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  web:
    image: artigo/web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - type: bind
        source: ./web/
        target: /web
    working_dir: /web
    depends_on:
      - api
    env_file:
      - ./.env
    ports:
      - "8080:80"
      - "8081:8080"

  grafana-db:
    image: postgres:14
    volumes:
      - grafana-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grafana
    env_file:
      - ./monitoring/.grafana-db.env

  grafana:
    image: grafana/grafana
    ports:
      - 8083:3000
    environment:
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-db:5432
      - GF_DATABASE_MAX_OPEN_CONN=300
    volumes:
      - grafana:/var/lib/grafana
    env_file:
       - ./monitoring/.grafana.env
    depends_on:
      - grafana-db

  influxdb:
    image: influxdb
    volumes:
      - influxdb:/root/.influxdbv2
    env_file:
       - ./monitoring/.influxdb.env

  telegraf:
    image: telegraf
    environment:
      - HOST_PROC=/host/proc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - ./monitoring/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb

volumes:
  influxdb:
  grafana:
  grafana-db: