version: "3.2"

services:
  redisai:
    image: redislabs/redisai:edge-cpu-bionic

  memcached:
    image: memcached:1
    restart: always
    command: -I 32m

  opensearch:
    image: opensearchproject/opensearch:latest
    restart: always
    environment:
      - node.name=os01
      - discovery.seed_hosts=os01
      - cluster.initial_master_nodes=os01
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
    volumes:
      # - ./search/config/perf/:/usr/share/opensearch/data/
      - ./search/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  db:
    image: postgres:14
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artigo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  search:
    image: artigo/search
    restart: always
    build:
      context: ./search
    volumes:
      - type: bind
        source: ./dump/
        target: /dump
      - type: bind
        source: ./search/
        target: /search
      - type: bind
        source: ./search/config.json
        target: /config.json
    working_dir: /search/src/artigo_search
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/search/src/
      # - GRPC_VERBOSITY=debug
    depends_on:
      - api
      - redisai

  api:
    image: artigo/api
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - type: bind
        source: ./media/
        target: /media
      - type: bind
        source: ./dump/
        target: /dump
      - type: bind
        source: ./api/
        target: /api
      - type: bind
        source: ./api/config.json
        target: /config.json
    working_dir: /api/src/artigo_api
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
    depends_on:
      - db
      - redisai
      - memcached
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  web:
    image: artigo/web
    restart: always
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - type: bind
        source: ./web/
        target: /web
    working_dir: /web
    depends_on:
      - api
    env_file:
      - ./.env
    ports:
      - "8080:80"
      - "8081:8080"
