version: "3.2"
services:
  redisai:
    image: redislabs/redisai:edge-cpu-bionic
    ports:
      - "127.0.0.1:6379:6379"

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - node.name=os01
      - discovery.seed_hosts=os01
      - cluster.initial_master_nodes=os01
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
    volumes:
      - ./opensearch/:/usr/share/opensearch/data
      - ./search/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9600:9600"

  db:
    image: postgres:13
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artigo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"

  search:
    image: artigo/search
    build:
      context: ./search
    volumes:
      - type: bind
        source: ./dump/
        target: /dump
      - type: bind
        source: ./search/
        target: /search
      - type: bind
        source: ./search/config.json
        target: /config.json
    working_dir: /search/src/artigo_search
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/search/src/
      # - GRPC_VERBOSITY=debug
    network_mode: "host"

  api:
    image: artigo/api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - type: bind
        source: ./media/
        target: /media
      - type: bind
        source: ./dump/
        target: /dump
      - type: bind
        source: ./api/
        target: /api
    working_dir: /api/src/artigo_api
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
    depends_on:
      - db
      - search
      - redisai
    ports:
      - "127.0.0.1:8000:8000"
# Activate again when shipping container
#    env_file:
#      - ./api/src/artigo_api/.env
    
  web:
    image: artigo/web
    build:
      context: ./web
    volumes:
      - type: bind
        source: ./web/
        target: /web
    working_dir: /web
    depends_on:
      - api
    ports:
      - "127.0.0.1:80:80"
      # Only for development
      - "127.0.0.1:8080:8080"
