version: "3.2"

services:
  redisai:
    image: redis:latest

  memcached:
    image: memcached:1
    command: -I 32m

  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - node.name=os01
      - discovery.seed_hosts=os01
      - cluster.initial_master_nodes=os01
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
    volumes:
      # - ./search/config/perf/:/usr/share/opensearch/data/
      - ./search/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  db:
    image: postgres:14
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artigo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  search:
    image: artigo/search
    build:
      context: .
      dockerfile: ./search/Dockerfile.dev
    volumes:
      - ./dump/:/dump
      - ./search/:/search
    working_dir: /search/src/artigo_search
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/search/src/
      - C_FORCE_ROOT=true
    depends_on:
      - api
      - redisai
    env_file:
      - ./.env

  api:
    image: artigo/api
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    volumes:
      - ./media/:/media
      - ./dump/:/dump
      - ./api/:/api
      - ./plugin.config.json:/config.json
    working_dir: /api/src/artigo_api
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/src/
      - C_FORCE_ROOT=true
    depends_on:
      - db
      - redisai
      - memcached
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  web:
    image: artigo/web
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
    volumes:
      - ./web/:/web
      - ./plugin.config.json:/config.json
    working_dir: /web
    depends_on:
      - api
    ports:
      - "8080:80"
      - "8081:8080"
