FROM python:3.10

ENV POETRY_VIRTUALENVS_CREATE=False

RUN pip install --no-cache-dir poetry pytest pytest-cov

COPY /search/pyproject.toml /search/poetry.lock /
RUN cd /search; poetry install

COPY /search /search/
RUN pip install /search

COPY /search/config.json /config.json

COPY /search/docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
