FROM python:3.9

RUN pip install pip --upgrade
RUN pip install poetry
RUN pip install pytest pytest-cov

COPY /search/pyproject.toml /search/poetry.lock /
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes
RUN pip install -r requirements.txt

COPY /search /search/
RUN pip install /search

COPY /search/config.json /config.json

COPY /search/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
