cluster.name: os-cluster
network.host: 0.0.0.0

bootstrap.memory_lock: "true"

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 93%
cluster.routing.allocation.disk.watermark.high: 95%

plugins.security.disabled: true
