# Generated by Django 4.0.3 on 2022-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
