# Generated by Django 4.0.4 on 2022-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertagging',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
