# Generated by Django 4.0.2 on 2022-03-14 09:06

from django.db import migrations, models
import frontend.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=frontend.fields.NameField(max_length=256),
        ),
        migrations.AddField(
            model_name='gameround',
            name='score_types',
            field=models.ManyToManyField(blank=True, null=True, to='frontend.ScoreType'),
        ),
    ]
