# Generated by Django 3.2.9 on 2021-11-17 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ArtStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ArtTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChosenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CombinedTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.tag')),
                ('gameround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='Gamemode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('media_type', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('institution_url', models.URLField(max_length=256)),
                ('resource_url', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WebPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('language', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='source',
        ),
        migrations.AddField(
            model_name='creator',
            name='born',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='died',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='nationality',
            field=models.CharField(default='english', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='media_type',
            field=models.CharField(default='jpg', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagging',
            name='origin',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='webpages',
            name='about_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.creator'),
        ),
        migrations.AddField(
            model_name='webpages',
            name='about_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.title'),
        ),
        migrations.AddField(
            model_name='combinedtagging',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.resource'),
        ),
        migrations.AddField(
            model_name='combinedtagging',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creator',
            name='locations',
            field=models.ManyToManyField(to='frontend.Location'),
        ),
        migrations.AddField(
            model_name='creator',
            name='techniques',
            field=models.ManyToManyField(to='frontend.ArtTechnique'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='gamemode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.gamemode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagging',
            name='media_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.gamemode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='movement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.artmovement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.artstyle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='technique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.arttechnique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.institution'),
        ),
    ]
