# Generated by Django 4.0.2 on 2022-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_scoretype_alter_tag_name_gameround_score_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='score_types',
            field=models.ManyToManyField(to='frontend.ScoreType'),
        ),
    ]
