# Generated by Django 4.0.3 on 2022-03-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_customuser_is_anonymous'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagging',
            new_name='UserTagging',
        ),
    ]
