# Generated by Django 4.0.4 on 2022-05-17 07:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_usertagging_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='gametype',
            new_name='game_type',
        ),
        migrations.CreateModel(
            name='UserROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('y', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('width', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('height', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('suggested', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('gameround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.gameround')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='frontend.resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TabooROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('y', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('width', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('height', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('gameround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.gameround')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpponentROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('y', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('width', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('height', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_after', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gameround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.gameround')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
