# Generated by Django 4.0.4 on 2022-05-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_gameround_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.resource'),
            preserve_default=False,
        ),
    ]
