# Generated by Django 4.1.3 on 2022-11-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_gameround_user_alter_gamesession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameroundParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_type', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('gameround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='frontend.gameround')),
            ],
        ),
    ]
