# Generated by Django 4.1.5 on 2023-02-01 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_gameroundparameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hash_id", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("access", models.CharField(choices=[("O", "Open"), ("R", "Restricted")], default="R", max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[("U", "Uploading"), ("F", "Finished"), ("E", "Error")], default="U", max_length=2
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
