# Generated by Django 4.1.6 on 2023-02-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0010_alter_resource_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="frontend.collection",
            ),
        ),
    ]
