# Generated by Django 4.1.7 on 2023-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0012_rename_date_collection_created_alter_userroi_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="access",
            field=models.CharField(
                choices=[("O", "Open"), ("P", "Pending"), ("R", "Restricted")], default="R", max_length=2
            ),
        ),
    ]
