# Generated by Django 4.1.7 on 2023-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0015_alter_collection_titles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputtagging",
            name="gameround",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="frontend.gameround",
            ),
        ),
        migrations.AlterField(
            model_name="opponenttagging",
            name="gameround",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="frontend.gameround",
            ),
        ),
        migrations.AlterField(
            model_name="tabootagging",
            name="gameround",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="frontend.gameround",
            ),
        ),
        migrations.AlterField(
            model_name="usertagging",
            name="gameround",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="frontend.gameround",
            ),
        ),
    ]
