# Generated by Django 4.1.7 on 2023-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0016_alter_inputtagging_gameround_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color_term",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="in_dictionary",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="technical_term",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
