# Generated by Django 5.2 on 2025-05-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0017_tag_color_term_tag_in_dictionary_tag_technical_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="frontend.collection",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_start",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="source",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="frontend.source"
            ),
        ),
    ]
