FROM ubuntu:20.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing -y
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install python3-pip npm libpq-dev -y

RUN pip install pip --upgrade
RUN pip install poetry
RUN pip install pytest pytest-cov

COPY /api/pyproject.toml /api/poetry.lock /api/
RUN cd /api; poetry export -f requirements.txt --output requirements.txt --without-hashes
RUN cd /api; pip install -r requirements.txt

COPY /search/pyproject.toml /search/poetry.lock /search/
RUN cd /search; poetry export -f requirements.txt --output requirements.txt  --without-hashes
RUN cd /search; pip install -r requirements.txt

COPY /search /search/
RUN pip install /search

COPY /api /api/
COPY plugin.config.json /config.json

ENV PYTHONPATH=/api/src/
WORKDIR /api/src/artigo_api

COPY /api/docker-entrypoint.dev.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
