FROM python:3.10

ENV PYTHONPATH=/api/src/ \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1
    
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        graphviz \
        graphviz-dev \
    && rm -rf /var/lib/apt/lists/*
    
RUN pip install --no-cache-dir poetry

RUN addgroup --system --gid 1998 artigo \
    && adduser --system --ingroup artigo --uid 1999 artigo

COPY /api/pyproject.toml /api/poetry.lock ./api/
RUN cd /api; poetry install --no-root

COPY /search/pyproject.toml /search/poetry.lock ./search/
RUN cd /search; poetry install --no-root

COPY --chown=artigo:artigo /api /api/
COPY --chown=artigo:artigo /search /search/
RUN pip install --no-cache-dir /search

COPY --chown=artigo:artigo plugin.config.json /config.json

WORKDIR /api/src/artigo_api

COPY /api/docker-entrypoint.sh /api/docker-entrypoint.sh
ENTRYPOINT ["/api/docker-entrypoint.dev.sh"]
