FROM python:3.10

ENV PYTHONPATH=/api/src/
ENV POETRY_VIRTUALENVS_CREATE=False

RUN addgroup --system --gid 1998 artigo \
    && adduser --system --ingroup artigo --uid 1999 artigo

RUN apt update && apt install -y build-essential python-dev graphviz graphviz-dev
RUN pip install --no-cache-dir poetry pytest pytest-cov

COPY /api/pyproject.toml /api/poetry.lock /api/
RUN cd /api; poetry install -vvv

COPY /search/pyproject.toml /search/poetry.lock /search/
RUN cd /search; poetry install -vvv

COPY --chown=artigo:artigo /api /api/
COPY --chown=artigo:artigo /search /search/
RUN pip install /search

COPY --chown=artigo:artigo plugin.config.json /config.json

WORKDIR /api/src/artigo_api

ENTRYPOINT ["/api/docker-entrypoint.dev.sh"]
